language: node_js
sudo: required
dist: xenial

addons:
    apt:
      packages:
        - xvfb

before_install:
  - sudo add-apt-repository ppa:ubuntu-wine/ppa -y
  - sudo apt-get update -q
  - sudo apt-get install -y wine1.7

install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - nvm install --lts=carbon
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - source ~/.bashrc
  - yarn

script:
  - yarn run build

branches:
  only:
  - master
